#!/usr/bin/env bash

# Credit to ThePrimeagen

if [[ $# -eq 1 ]]; then
    selected=$1
else
    # Check for Development directory (macOS) or development directory (Linux)
    if [ -d "$HOME/Development" ]; then
        dev_dir="$HOME/Development"
    elif [ -d "$HOME/development" ]; then
        dev_dir="$HOME/development"
    else
        dev_dir="$HOME"
    fi
    items=`find "$dev_dir" -maxdepth 2 -mindepth 1 -type d`
    items+=`echo -e "\n/tmp"`
    selected=`echo "$items" | fzf`
fi

if [[ $selected == '' ]]; then
    exit
fi

dirname=`basename "$selected" | sed 's/\./_/g'`

tmux switch-client -t ="$dirname"
if [[ $? -eq 0 ]]; then
    exit 0
fi

tmux new-session -c "$selected" -d -s "$dirname" && tmux switch-client -t "$dirname" || tmux new -c "$selected" -A -s "$dirname"
