local set = vim.keymap.set

set("n", "<leader><leader>x", "<cmd>source %<CR>")
set("n", "<leader>x", ":.lua<CR>")
set("v", "<leader>x", ":lua<CR>")
set("n", "<M-n>", "<cmd>cnext<cr>")
set("n", "<M-p>", "<cmd>cprev<cr>")
set("n", "-", ":Oil<cr>")
set("t", "<esc><esc>", "<C-\\><C-n>", {})
set("n", "k", "v:count == 0 ? 'gk' : 'k'", { expr = true })
set("n", "j", "v:count == 0 ? 'gj' : 'j'", { expr = true })
set("v", "<", "<gv")
set("v", ">", ">gv")
set("v", "y", "myy`y")
set("n", "p", '"_dP')
set("i", ";;", "<ESC>A;")
set("i", ",,", "<ESC>A,")
set("n", "<leader>k", ":nohlsearch<cr>")
set("n", "<leader>o", ":!open %<cr><cr>")
set("i", "<A-j>", "<Esc>:move .+1<CR>==gi")
set("i", "<A-k>", "<Esc>:move .-2<CR>==gi")
set("n", "<A-j>", ":move .+1<CR>==")
set("n", "<A-k>", ":move .-2<CR>==")
set("v", "<A-j>", ":move '>+1<CR>gv=gv")
set("v", "<A-k>", ":move '<-2<CR>gv=gv")
set("n", "<A-->", ":resize +2<CR>")
set("n", "<A-=>", ":resize -2<CR>")
set("n", "<A-,>", ":vertical resize -2<CR>")
set("n", "<A-.>", ":vertical resise +2<CR>")
set("n", "<leader>d", vim.diagnostic.open_float)
set("n", "grr", ":silent Telescope lsp_references<CR>")
set("n", "gri", ":silent Telescope lsp_implementations<CR>")
set("n", "grd", ":silent Telescope lsp_definitions<CR>")
set("n", "gO", ":silent Telescope lsp_document_symbols<CR>")
set("n", "gra", vim.lsp.buf.code_action)
set("n", "<leader>rn", vim.lsp.buf.rename)
set({ "n", "v" }, "<leader>y", '"+y')
set({ "n", "v" }, "<leader>p", '"+p')

set({ "n", "v" }, "<leader>p", '"+p', { noremap = true, desc = "Past from system clipboard" })
set({ "n", "v" }, "<leader>y", '"+y', { noremap = true, desc = "yank to system clipboard" })
